version: '3.8'

services:
  stock-service:
    build: ./stock_details
    ports:
      - "8001:8000"
    depends_on:
      - postgres_db
    env_file:
      - .env

  company-service:
    build: ./company_details
    ports:
      - "8002:8000"
    depends_on:
      - postgres_db
    env_file:
      - .env

  news-service:
    build: ./news_service
    ports:
      - "8003:8000"
    depends_on:
      - postgres_db
    env_file:
      - .env

  postgres_db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: stock_data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
